openapi: 3.0.0
info:
  description: API for registering and managing data center facilities
  title: Facility Registry API
  version: 1.0.0
servers:
- description: Registry API v1
  url: https://api.registry.example.com/v1
tags:
- description: |
    The following metrics are supported for streaming time series data. When registering a facility, you will receive the endpoint information as well as labels for Prometheus.

    ## Energy Metrics
    - `heatpump_power_consumption_joules`: Heat pump electricity consumption
    - `office_energy_use_joules`: Office electricity consumption
    - `total_generator_energy_joules`: Generator energy output
    - `grid_transformers_energy_joules`: Transformer energy output
    - `onsite_renewable_energy_joules`: On-site renewable energy production
    - `it_power_usage_level1_joules`: IT power at UPS output
    - `it_power_usage_level2_joules`: IT power at PDU output
    - `renewable_energy_certificates_joules`: Green energy certificates
    - `grid_emission_factor_grams`: The current grid emission factor (g/CO2-eq per kWh)
    - `backup_emission_factor_grams`: The current backup power emission factor (g/CO2-eq per kWh)
    - `electricity_source`: 1 for grid; 2 for backup generators
    - `pue_1_ratio`: Power usage effectiveness measured from the output of the UPS systems for IT load
    - `pue_2_ratio`: Power usage effectiveness measured from the output of the PDU systems for IT load

    ## Water Usage Metrics
    - `dc_water_usage_cubic_meters`: Data center water consumption
    - `office_water_usage_cubic_meters`: Office water consumption

    ## Operational Metrics
    - `generator_load_factor_ratio`: Generator load factor (0-1)
  name: Supported Time Series Metrics for Facilities
  x-displayName: Supported Time Series Metrics for Facilities
- name: facility-api.spec_other
  x-displayName: other
- description: |
    The following metrics are supported for streaming time series data:

    ## Energy Metrics
    - `pdu_N_energy_consumption_joules`: PDU energy consumption readings
      - Multiple metrics exist based on the number of PDUs in the rack
      - Example for a rack with 2 PDUs:
        - `pdu_1_energy_consumption_joules`
        - `pdu_2_energy_consumption_joules`

    ## Temperature Metrics
    - `inlet_temperature_celsius`: Inlet cooling temperature
    - `outlet_temperature_celsius`: Outlet cooling temperature
  name: Supported Time Series Metrics for Racks
  x-displayName: Supported Time Series Metrics for Racks
- name: rack-api.spec_other
  x-displayName: other
- description: |
    The following metrics are supported for streaming time series data:

    ## Energy Metrics
    - `cpu_energy_consumption_joules`: CPU energy consumption via RAPL
    - `server_energy_consumption_joules`: Total server energy consumption via IPMI
  name: Supported Time Series Metrics for Servers
  x-displayName: Supported Time Series Metrics for Servers
- name: server-api.spec_other
  x-displayName: other
paths:
  /facilities:
    get:
      description: Retrieve a list of all registered facilities
      operationId: list_facilities
      parameters:
      - description: Maximum number of facilities to return
        explode: true
        in: query
        name: limit
        required: false
        schema:
          default: 20
          type: integer
        style: form
      - description: Number of facilities to skip
        explode: true
        in: query
        name: offset
        required: false
        schema:
          default: 0
          type: integer
        style: form
      responses:
        "200":
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/listFacilities_200_response'
          description: List of facilities
      summary: List all facilities
      tags:
      - facility-api.spec_other
      x-openapi-router-controller: nadiki_registrar.controllers.facility_api_spec_other_controller
    post:
      description: Create a new facility entry in the registry
      operationId: create_facility
      requestBody:
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/FacilityCreate'
        required: true
      responses:
        "201":
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/FacilityResponse'
          description: Facility successfully created
        "400":
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Error'
          description: Invalid input
      summary: Register a new facility
      tags:
      - facility-api.spec_other
      x-openapi-router-controller: nadiki_registrar.controllers.facility_api_spec_other_controller
  /facilities/{facilityId}:
    delete:
      description: Remove a facility from the registry
      operationId: delete_facility
      parameters:
      - description: Unique facility identifier
        explode: false
        in: path
        name: facilityId
        required: true
        schema:
          type: string
        style: simple
      responses:
        "204":
          description: Facility successfully deleted
        "404":
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Error'
          description: Facility not found
      summary: Delete facility
      tags:
      - facility-api.spec_other
      x-openapi-router-controller: nadiki_registrar.controllers.facility_api_spec_other_controller
    get:
      description: Retrieve detailed information about a specific facility
      operationId: get_facility
      parameters:
      - description: Unique facility identifier
        explode: false
        in: path
        name: facilityId
        required: true
        schema:
          type: string
        style: simple
      responses:
        "200":
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/FacilityResponse'
          description: Facility details
        "404":
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Error'
          description: Facility not found
      summary: Get facility details
      tags:
      - facility-api.spec_other
      x-openapi-router-controller: nadiki_registrar.controllers.facility_api_spec_other_controller
    put:
      description: Update all facility information
      operationId: update_facility
      parameters:
      - description: Unique facility identifier
        explode: false
        in: path
        name: facilityId
        required: true
        schema:
          type: string
        style: simple
      requestBody:
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/FacilityUpdate'
        required: true
      responses:
        "200":
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/FacilityResponse'
          description: Facility successfully updated
        "400":
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Error'
          description: Invalid input
        "404":
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Error'
          description: Facility not found
      summary: Update facility
      tags:
      - facility-api.spec_other
      x-openapi-router-controller: nadiki_registrar.controllers.facility_api_spec_other_controller
  /racks:
    get:
      description: Retrieve a list of all registered racks
      operationId: list_racks
      parameters:
      - description: Maximum number of racks to return
        explode: true
        in: query
        name: limit
        required: false
        schema:
          default: 20
          type: integer
        style: form
      - description: Number of racks to skip
        explode: true
        in: query
        name: offset
        required: false
        schema:
          default: 0
          type: integer
        style: form
      - description: Filter racks by facility ID
        explode: true
        in: query
        name: facility_id
        required: false
        schema:
          type: string
        style: form
      responses:
        "200":
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/listRacks_200_response'
          description: List of racks
      summary: List all racks
      tags:
      - rack-api.spec_other
      x-openapi-router-controller: nadiki_registrar.controllers.rack_api_spec_other_controller
    post:
      description: Create a new rack entry in the registry
      operationId: create_rack
      requestBody:
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/RackCreate'
        required: true
      responses:
        "201":
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/RackResponse'
          description: Rack successfully created
        "400":
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Error'
          description: Invalid input
      summary: Register a new rack
      tags:
      - rack-api.spec_other
      x-openapi-router-controller: nadiki_registrar.controllers.rack_api_spec_other_controller
  /racks/{rackId}:
    delete:
      description: Remove a rack from the registry
      operationId: delete_rack
      parameters:
      - description: "Unique rack identifier (format RACK-[FACILITY_ID]-[RACK_ID])"
        explode: false
        in: path
        name: rackId
        required: true
        schema:
          type: string
        style: simple
      responses:
        "204":
          description: Rack successfully deleted
        "404":
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Error'
          description: Rack not found
      summary: Delete rack
      tags:
      - rack-api.spec_other
      x-openapi-router-controller: nadiki_registrar.controllers.rack_api_spec_other_controller
    get:
      description: Retrieve detailed information about a specific rack
      operationId: get_rack
      parameters:
      - description: "Unique rack identifier (format RACK-[FACILITY_ID]-[RACK_ID])"
        explode: false
        in: path
        name: rackId
        required: true
        schema:
          type: string
        style: simple
      responses:
        "200":
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/RackResponse'
          description: Rack details
        "404":
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Error'
          description: Rack not found
      summary: Get rack details
      tags:
      - rack-api.spec_other
      x-openapi-router-controller: nadiki_registrar.controllers.rack_api_spec_other_controller
    put:
      description: Update all rack information
      operationId: update_rack
      parameters:
      - description: "Unique rack identifier (format RACK-[FACILITY_ID]-[RACK_ID])"
        explode: false
        in: path
        name: rackId
        required: true
        schema:
          type: string
        style: simple
      requestBody:
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/RackUpdate'
        required: true
      responses:
        "200":
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/RackResponse'
          description: Rack successfully updated
        "400":
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Error'
          description: Invalid input
        "404":
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Error'
          description: Rack not found
      summary: Update rack
      tags:
      - rack-api.spec_other
      x-openapi-router-controller: nadiki_registrar.controllers.rack_api_spec_other_controller
  /servers:
    get:
      description: Retrieve a list of all registered servers
      operationId: list_servers
      parameters:
      - description: Maximum number of servers to return
        explode: true
        in: query
        name: limit
        required: false
        schema:
          default: 20
          type: integer
        style: form
      - description: Number of servers to skip
        explode: true
        in: query
        name: offset
        required: false
        schema:
          default: 0
          type: integer
        style: form
      - description: Filter servers by facility ID
        explode: true
        in: query
        name: facility_id
        required: false
        schema:
          type: string
        style: form
      - description: Filter servers by rack ID
        explode: true
        in: query
        name: rack_id
        required: false
        schema:
          type: string
        style: form
      responses:
        "200":
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/listServers_200_response'
          description: List of servers
      summary: List all servers
      tags:
      - server-api.spec_other
      x-openapi-router-controller: nadiki_registrar.controllers.server_api_spec_other_controller
    post:
      description: Create a new server entry in the registry
      operationId: create_server
      requestBody:
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/ServerCreate'
        required: true
      responses:
        "201":
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/ServerResponse'
          description: Server successfully created
        "400":
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Error'
          description: Invalid input
      summary: Register a new server
      tags:
      - server-api.spec_other
      x-openapi-router-controller: nadiki_registrar.controllers.server_api_spec_other_controller
  /servers/{serverId}:
    delete:
      description: Remove a server from the registry
      operationId: delete_server
      parameters:
      - description: "Unique server identifier (format SERVER-[FACILITY_ID]-[RACK_ID]-[SERVER_ID])"
        explode: false
        in: path
        name: serverId
        required: true
        schema:
          type: string
        style: simple
      responses:
        "204":
          description: Server successfully deleted
        "404":
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Error'
          description: Server not found
      summary: Delete server
      tags:
      - server-api.spec_other
      x-openapi-router-controller: nadiki_registrar.controllers.server_api_spec_other_controller
    get:
      description: Retrieve detailed information about a specific server
      operationId: get_server
      parameters:
      - description: "Unique server identifier (format SERVER-[FACILITY_ID]-[RACK_ID]-[SERVER_ID])"
        explode: false
        in: path
        name: serverId
        required: true
        schema:
          type: string
        style: simple
      responses:
        "200":
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/ServerResponse'
          description: Server details
        "404":
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Error'
          description: Server not found
      summary: Get server details
      tags:
      - server-api.spec_other
      x-openapi-router-controller: nadiki_registrar.controllers.server_api_spec_other_controller
    put:
      description: Update all server information
      operationId: update_server
      parameters:
      - description: "Unique server identifier (format SERVER-[FACILITY_ID]-[RACK_ID]-[SERVER_ID])"
        explode: false
        in: path
        name: serverId
        required: true
        schema:
          type: string
        style: simple
      requestBody:
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/ServerUpdate'
        required: true
      responses:
        "200":
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/ServerResponse'
          description: Server successfully updated
        "400":
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Error'
          description: Invalid input
        "404":
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Error'
          description: Server not found
      summary: Update server
      tags:
      - server-api.spec_other
      x-openapi-router-controller: nadiki_registrar.controllers.server_api_spec_other_controller
components:
  schemas:
    Location:
      example:
        latitude: -75.58509
        longitude: 36.988422
      properties:
        latitude:
          description: Latitude coordinate of the facility
          format: float
          maximum: 90
          minimum: -90
          title: latitude
          type: number
        longitude:
          description: Longitude coordinate of the facility
          format: float
          maximum: 180
          minimum: -180
          title: longitude
          type: number
      required:
      - latitude
      - longitude
      title: Location
      type: object
    FacilityCreate:
      example:
        embeddedGhgEmissionsFacility: 1.4658129
        maintenanceHoursGenerator: 3.6160767
        whiteSpace: 6.846853
        designPue: 1.7386281
        description: description
        coolingFluids:
        - amount: 7.0614014
          gwpFactor: 9.301444
          type: type
        - amount: 7.0614014
          gwpFactor: 9.301444
          type: type
        totalSpace: 1.4894159
        gridPowerFeeds: 1
        lifetimeFacility: 1
        whiteSpaceFloors: 1
        installedCapacity: 2.027123
        lifetimeAssets: 1
        tierLevel: 1
        location:
          latitude: -75.58509
          longitude: 36.988422
        embeddedGhgEmissionsAssets: 5.637377
      properties:
        location:
          $ref: '#/components/schemas/Location'
        embeddedGhgEmissionsFacility:
          description: Embodied carbon emissions from facility construction (CO2-eq)
          format: float
          title: embeddedGhgEmissionsFacility
          type: number
        lifetimeFacility:
          default: 15
          description: Expected lifetime of the facility in years
          minimum: 1
          title: lifetimeFacility
          type: integer
        embeddedGhgEmissionsAssets:
          description: Sum of GHG emissions embodied in assets
          format: float
          title: embeddedGhgEmissionsAssets
          type: number
        lifetimeAssets:
          default: 10
          description: Expected average lifetime of assets in years
          minimum: 1
          title: lifetimeAssets
          type: integer
        coolingFluids:
          items:
            $ref: '#/components/schemas/FacilityCreate_coolingFluids_inner'
          title: coolingFluids
          type: array
        maintenanceHoursGenerator:
          description: Annual maintenance runtime hours for generators
          format: float
          title: maintenanceHoursGenerator
          type: number
        installedCapacity:
          description: Installed/rated power capacity (watts)
          format: float
          title: installedCapacity
          type: number
        gridPowerFeeds:
          default: 3
          description: Number of physical power feeds
          minimum: 1
          title: gridPowerFeeds
          type: integer
        designPue:
          default: 1.4
          description: Design Power Usage Effectiveness
          format: float
          minimum: 1
          title: designPue
          type: number
        tierLevel:
          default: 3
          description: Certified/rated tier level
          enum:
          - 1
          - 2
          - 3
          - 4
          title: tierLevel
          type: integer
        whiteSpaceFloors:
          default: 1
          description: Number of floors used for white space
          minimum: 1
          title: whiteSpaceFloors
          type: integer
        totalSpace:
          description: Total facility space (m2)
          format: float
          title: totalSpace
          type: number
        whiteSpace:
          description: Total white space (m2)
          format: float
          title: whiteSpace
          type: number
        description:
          description: Textual description ob the facility for informational purposes
          title: description
          type: string
      required:
      - location
      title: FacilityCreate
      type: object
    FacilityUpdate:
      allOf:
      - $ref: '#/components/schemas/FacilityCreate'
      - required:
        - location
        type: object
      title: FacilityUpdate
    FacilityTimeSeriesDataPoint:
      properties:
        measurement:
          description: Name of the Influx measurement
          enum:
          - facility
          - rack
          - server
          title: measurement
          type: string
        field:
          description: Metric name with unit suffix
          enum:
          - heatpump_avg_watts
          - office_avg_watts
          - dc_water_usage_cubic_meters
          - office_water_usage_cubic_meters
          - total_generator_avg_watts
          - generator_load_factor_ratio
          - grid_transformers_avg_watts
          - onsite_renewable_energy_avg_watts
          - it_power_usage_level1_avg_watts
          - it_power_usage_level2_avg_watts
          - renewable_energy_certificates_watts
          - grid_emission_factor_grams
          - backup_emission_factor_grams
          - electricity_source
          - pue_1_ratio
          - pue_2_ratio
          title: field
          type: string
        granularitySeconds:
          default: 30
          description: Time series data granularity in seconds
          title: granularitySeconds
          type: integer
        tags:
          $ref: '#/components/schemas/FacilityTimeSeriesDataPoint_tags'
      required:
      - field
      - granularitySeconds
      - measurement
      - tags
      title: FacilityTimeSeriesDataPoint
      type: object
    FacilityTimeSeriesConfig:
      properties:
        endpoint:
          description: InfluxDB endpoint URL with port number
          example: https://timeseries.registry.example.com:8086
          title: endpoint
          type: string
        org:
          description: InfluxDB organization to use
          example: leitmotiv
          title: org
          type: string
        bucket:
          description: InfluxDB bucket to send data to
          example: my-bucket
          title: bucket
          type: string
        token:
          description: InfluxDB token to use for authentication
          example: ABCDEFGHIJK
          title: token
          type: string
        dataPoints:
          description: List of time series metrics available for streaming
          items:
            $ref: '#/components/schemas/FacilityTimeSeriesDataPoint'
          title: dataPoints
          type: array
      required:
      - bucket
      - dataPoints
      - endpoint
      - org
      - token
      title: FacilityTimeSeriesConfig
      type: object
    FacilityResponse:
      allOf:
      - $ref: '#/components/schemas/FacilityCreate'
      - $ref: '#/components/schemas/FacilityResponse_allOf'
      title: FacilityResponse
    Error:
      properties:
        code:
          description: Error code
          title: code
          type: string
        message:
          description: Error message
          title: message
          type: string
        details:
          description: Additional error details
          title: details
          type: object
      required:
      - code
      - message
      title: Error
      type: object
    RackCreate:
      example:
        total_available_cooling_capacity: 6.0274563
        total_available_power: 0.8008282
        number_of_pdus: 1
        product_passport: "{}"
        power_redundancy: 1
        facility_id: facility_id
        description: description
      properties:
        facility_id:
          description: ID of the facility where the rack is located
          title: facility_id
          type: string
        total_available_power:
          default: 5
          description: Total available power in kW
          format: float
          title: total_available_power
          type: number
        total_available_cooling_capacity:
          default: 5
          description: Total available cooling capacity in kW
          format: float
          title: total_available_cooling_capacity
          type: number
        number_of_pdus:
          default: 2
          description: Number of PDUs in the rack
          minimum: 1
          title: number_of_pdus
          type: integer
        power_redundancy:
          default: 2
          description: Number of power feeds used for redundancy
          minimum: 1
          title: power_redundancy
          type: integer
        product_passport:
          description: LCA product passport data
          title: product_passport
          type: object
        description:
          description: Textual description ob the facility for informational purposes
          title: description
          type: string
      required:
      - facility_id
      title: RackCreate
      type: object
    RackUpdate:
      allOf:
      - $ref: '#/components/schemas/RackCreate'
      - required:
        - facility_id
        type: object
      title: RackUpdate
    RackTimeSeriesDataPoint:
      properties:
        measurement:
          description: Name of the Influx measurement
          enum:
          - facility
          - rack
          - server
          title: measurement
          type: string
        field:
          description: "Prometheus metric name with unit suffix. For PDU metrics,\
            \ \nthe name must follow the pattern 'pdu_N_energy_consumption_joules'\
            \ \nwhere N is the PDU number (1 to number_of_pdus)\n"
          pattern: "/^(pdu_[1-9][0-9]*_energy_consumption_joules|inlet_temperature_celsius|outlet_temperature_celsius)$/"
          title: field
          type: string
        granularitySeconds:
          default: 30
          description: Time series data granularity in seconds
          title: granularitySeconds
          type: integer
        tags:
          $ref: '#/components/schemas/RackTimeSeriesDataPoint_tags'
      required:
      - field
      - granularitySeconds
      - measurement
      - tags
      title: RackTimeSeriesDataPoint
      type: object
    RackTimeSeriesConfig:
      properties:
        endpoint:
          description: InfluxDB endpoint URL with port number
          example: https://timeseries.registry.example.com:8086
          title: endpoint
          type: string
        org:
          description: InfluxDB organization to use
          example: leitmotiv
          title: org
          type: string
        bucket:
          description: InfluxDB bucket to send data to
          example: my-bucket
          title: bucket
          type: string
        token:
          description: InfluxDB token to use for authentication
          example: ABCDEFGHIJK
          title: token
          type: string
        dataPoints:
          description: List of time series metrics available for streaming
          items:
            $ref: '#/components/schemas/RackTimeSeriesDataPoint'
          title: dataPoints
          type: array
      required:
      - bucket
      - dataPoints
      - endpoint
      - org
      - token
      title: RackTimeSeriesConfig
      type: object
    RackResponse:
      allOf:
      - $ref: '#/components/schemas/RackCreate'
      - $ref: '#/components/schemas/RackResponse_allOf'
      title: RackResponse
    CPU:
      example:
        vendor: vendor
        type: type
        physical_core_count: 1
      properties:
        vendor:
          description: "CPU vendor (e.g., Intel, AMD)"
          title: vendor
          type: string
        type:
          description: CPU type identifier
          title: type
          type: string
        physical_core_count:
          minimum: 1
          title: physical_core_count
          type: integer
      required:
      - type
      - vendor
      title: CPU
      type: object
    GPU:
      example:
        vendor: vendor
        type: type
      properties:
        vendor:
          description: "GPU vendor (e.g., Nvidia, AMD)"
          title: vendor
          type: string
        type:
          description: GPU type identifier
          title: type
          type: string
      required:
      - type
      - vendor
      title: GPU
      type: object
    FPGA:
      example:
        vendor: vendor
        type: type
      properties:
        vendor:
          description: "FPGA vendor (e.g., Intel, Xilinx)"
          title: vendor
          type: string
        type:
          description: FPGA type identifier
          title: type
          type: string
      required:
      - type
      - vendor
      title: FPGA
      type: object
    StorageDevice:
      example:
        vendor: vendor
        type: NVMe
        capacity: 7.0614014
      properties:
        vendor:
          description: "Disk vendor (e.g., Samsung, Intel)"
          title: vendor
          type: string
        capacity:
          description: Disk capacity in TB
          format: float
          title: capacity
          type: number
        type:
          description: Type of storage device
          enum:
          - NVMe
          - SSD
          - HDD
          - Other
          title: type
          type: string
      required:
      - capacity
      - type
      - vendor
      title: StorageDevice
      type: object
    ServerCreate:
      example:
        number_of_psus: 1
        rated_power: 0.8008282
        installed_gpus:
        - vendor: vendor
          type: type
        - vendor: vendor
          type: type
        description: description
        total_cpu_sockets: 1
        storage_devices:
        - vendor: vendor
          type: NVMe
          capacity: 7.0614014
        - vendor: vendor
          type: NVMe
          capacity: 7.0614014
        total_installed_memory: 5
        cooling_type: air
        rack_id: rack_id
        installed_fpgas:
        - vendor: vendor
          type: type
        - vendor: vendor
          type: type
        product_passport: "{}"
        installed_cpus:
        - vendor: vendor
          type: type
          physical_core_count: 1
        - vendor: vendor
          type: type
          physical_core_count: 1
        facility_id: facility_id
        number_of_memory_units: 2
      properties:
        facility_id:
          description: ID of the facility where the server is located
          title: facility_id
          type: string
        rack_id:
          description: ID of the rack where the server is installed
          title: rack_id
          type: string
        rated_power:
          description: Rated power in kW
          format: float
          title: rated_power
          type: number
        total_cpu_sockets:
          default: 2
          description: Total number of CPU sockets
          minimum: 1
          title: total_cpu_sockets
          type: integer
        installed_cpus:
          description: Array of installed CPUs
          items:
            $ref: '#/components/schemas/CPU'
          title: installed_cpus
          type: array
        number_of_psus:
          default: 2
          description: Number of power supply units
          minimum: 1
          title: number_of_psus
          type: integer
        total_installed_memory:
          description: Total installed memory in GB
          title: total_installed_memory
          type: integer
        number_of_memory_units:
          description: Number of memory units installed
          title: number_of_memory_units
          type: integer
        storage_devices:
          description: Array of installed storage devices
          items:
            $ref: '#/components/schemas/StorageDevice'
          title: storage_devices
          type: array
        installed_gpus:
          description: Array of installed GPUs
          items:
            $ref: '#/components/schemas/GPU'
          title: installed_gpus
          type: array
        installed_fpgas:
          description: Array of installed FPGAs
          items:
            $ref: '#/components/schemas/FPGA'
          title: installed_fpgas
          type: array
        product_passport:
          description: LCA product passport data
          title: product_passport
          type: object
        cooling_type:
          default: air
          description: Type of cooling system used for this server
          enum:
          - direct-to-chip
          - immersion
          - back-door-liquid
          - back-door-fan
          - air
          title: cooling_type
          type: string
        description:
          description: Textual description ob the facility for informational purposes
          title: description
          type: string
      required:
      - cooling_type
      - facility_id
      - rack_id
      title: ServerCreate
      type: object
    ServerUpdate:
      allOf:
      - $ref: '#/components/schemas/ServerCreate'
      - required:
        - cooling_type
        - facility_id
        - rack_id
        type: object
      title: ServerUpdate
    ServerTimeSeriesDataPoint:
      properties:
        measurement:
          description: Name of the Influx measurement
          enum:
          - facility
          - rack
          - server
          title: measurement
          type: string
        field:
          description: Metric name with unit suffix
          pattern: /^(cpu_energy_consumption_joules|server_energy_consumption_joules)$/
          title: field
          type: string
        granularitySeconds:
          default: 30
          description: Time series data granularity in seconds
          title: granularitySeconds
          type: integer
        tags:
          $ref: '#/components/schemas/ServerTimeSeriesDataPoint_tags'
      required:
      - field
      - granularitySeconds
      - measurement
      - tags
      title: ServerTimeSeriesDataPoint
      type: object
    ServerTimeSeriesConfig:
      properties:
        endpoint:
          description: InfluxDB endpoint URL with port number
          example: https://timeseries.registry.example.com:8086
          title: endpoint
          type: string
        org:
          description: InfluxDB organization to use
          example: leitmotiv
          title: org
          type: string
        bucket:
          description: InfluxDB bucket to send data to
          example: my-bucket
          title: bucket
          type: string
        token:
          description: InfluxDB token to use for authentication
          example: ABCDEFGHIJK
          title: token
          type: string
        dataPoints:
          description: List of time series metrics available for streaming
          items:
            $ref: '#/components/schemas/ServerTimeSeriesDataPoint'
          title: dataPoints
          type: array
      required:
      - bucket
      - dataPoints
      - endpoint
      - org
      - token
      title: ServerTimeSeriesConfig
      type: object
    ServerResponse:
      allOf:
      - $ref: '#/components/schemas/ServerCreate'
      - $ref: '#/components/schemas/ServerResponse_allOf'
      title: ServerResponse
    listFacilities_200_response:
      example:
        total: 0
        offset: 1
        limit: 6
        items:
        - null
        - null
      properties:
        items:
          items:
            $ref: '#/components/schemas/FacilityResponse'
          title: items
          type: array
        total:
          description: Total number of facilities
          title: total
          type: integer
        limit:
          description: Number of facilities per page
          title: limit
          type: integer
        offset:
          description: Current offset
          title: offset
          type: integer
      title: listFacilities_200_response
      type: object
    listRacks_200_response:
      example:
        total: 0
        offset: 1
        limit: 6
        items:
        - null
        - null
      properties:
        items:
          items:
            $ref: '#/components/schemas/RackResponse'
          title: items
          type: array
        total:
          description: Total number of racks
          title: total
          type: integer
        limit:
          description: Number of racks per page
          title: limit
          type: integer
        offset:
          description: Current offset
          title: offset
          type: integer
      title: listRacks_200_response
      type: object
    listServers_200_response:
      example:
        total: 0
        offset: 1
        limit: 6
        items:
        - null
        - null
      properties:
        items:
          items:
            $ref: '#/components/schemas/ServerResponse'
          title: items
          type: array
        total:
          description: Total number of servers
          title: total
          type: integer
        limit:
          description: Number of servers per page
          title: limit
          type: integer
        offset:
          description: Current offset
          title: offset
          type: integer
      title: listServers_200_response
      type: object
    FacilityCreate_coolingFluids_inner:
      example:
        amount: 7.0614014
        gwpFactor: 9.301444
        type: type
      properties:
        type:
          description: Type identifier for the cooling fluid
          title: type
          type: string
        amount:
          description: Amount of cooling fluid (kg or m3)
          format: float
          title: amount
          type: number
        gwpFactor:
          description: Global Warming Potential factor for this fluid type
          format: float
          title: gwpFactor
          type: number
      required:
      - amount
      - type
      title: FacilityCreate_coolingFluids_inner
      type: object
    FacilityTimeSeriesDataPoint_tags:
      properties:
        facility_id:
          description: Facility identifier
          title: facility_id
          type: string
        country_code:
          description: ISO 3166-1 alpha-3 country code
          title: country_code
          type: string
      required:
      - country_code
      - facility_id
      title: FacilityTimeSeriesDataPoint_tags
      type: object
    FacilityResponse_allOf:
      properties:
        id:
          description: "Unique facility identifier (format FACILITY-[COUNTRY_CODE]-ID)"
          example: FACILITY-NLD-001
          title: id
          type: string
        countryCode:
          description: ISO 3166-1 alpha-3 country code derived from location
          example: NLD
          title: countryCode
          type: string
        timeSeriesConfig:
          $ref: '#/components/schemas/FacilityTimeSeriesConfig'
        createdAt:
          format: date-time
          title: createdAt
          type: string
        updatedAt:
          format: date-time
          title: updatedAt
          type: string
      required:
      - countryCode
      - id
      - location
      - timeSeriesConfig
      title: FacilityResponse_allOf
      type: object
      example: null
    RackTimeSeriesDataPoint_tags:
      properties:
        facility_id:
          description: Facility identifier
          title: facility_id
          type: string
        rack_id:
          description: "Rack identifier (format RACK-[FACILITY_ID]-[RACK_ID])"
          title: rack_id
          type: string
        country_code:
          description: ISO 3166-1 alpha-3 country code
          title: country_code
          type: string
      required:
      - country_code
      - facility_id
      - rack_id
      title: RackTimeSeriesDataPoint_tags
      type: object
    RackResponse_allOf:
      properties:
        id:
          description: "Unique rack identifier (format RACK-[FACILITY_ID]-[RACK_ID])"
          example: RACK-FACILITY-NLD-001-001
          title: id
          type: string
        timeSeriesConfig:
          $ref: '#/components/schemas/RackTimeSeriesConfig'
        createdAt:
          format: date-time
          title: createdAt
          type: string
        updatedAt:
          format: date-time
          title: updatedAt
          type: string
      required:
      - facility_id
      - id
      - timeSeriesConfig
      title: RackResponse_allOf
      type: object
      example: null
    ServerTimeSeriesDataPoint_tags:
      properties:
        facility_id:
          description: Facility identifier
          title: facility_id
          type: string
        rack_id:
          description: Rack identifier
          title: rack_id
          type: string
        server_id:
          description: "Server identifier (format SERVER-[FACILITY_ID]-[RACK_ID]-[SERVER_ID])"
          title: server_id
          type: string
        country_code:
          description: ISO 3166-1 alpha-3 country code
          title: country_code
          type: string
      required:
      - country_code
      - facility_id
      - rack_id
      - server_id
      title: ServerTimeSeriesDataPoint_tags
      type: object
    ServerResponse_allOf:
      properties:
        id:
          description: "Unique server identifier (format SERVER-[FACILITY_ID]-[RACK_ID]-[SERVER_ID])"
          example: SERVER-FACILITY-NLD-001-RACK-001-001
          title: id
          type: string
        timeSeriesConfig:
          $ref: '#/components/schemas/ServerTimeSeriesConfig'
        createdAt:
          format: date-time
          title: createdAt
          type: string
        updatedAt:
          format: date-time
          title: updatedAt
          type: string
      required:
      - id
      - timeSeriesConfig
      title: ServerResponse_allOf
      type: object
      example: null
  x-supported-facility-timeseries-metrics:
    description: List of all supported time series metrics for facility monitoring
    metrics:
    - name: heatpump_power_consumption_joules
      unit: Energy
      description: Amount of electricity used by the heat pump to generate heat
    - name: office_energy_use_joules
      unit: Energy
      description: Amount of electricity used by the office
    - name: dc_water_usage_cubic_meters
      unit: Length
      description: Amount of fresh water used by the DC (m3)
    - name: office_water_usage_cubic_meters
      unit: Length
      description: Amount of fresh water used by the office (m3)
    - name: total_generator_energy_joules
      unit: Energy
      description: Total energy output of the generators running
    - name: generator_load_factor_ratio
      unit: Percent
      description: Average load factor of all generators running
    - name: grid_transformers_energy_joules
      unit: Energy
      description: Sum of energy output of all transformers
    - name: onsite_renewable_energy_joules
      unit: Energy
      description: Sum of energy produced of all on-site renewable energy sources
    - name: it_power_usage_level1_joules
      unit: Energy
      description: Sum of power usage measured at UPS systems output
    - name: it_power_usage_level2_joules
      unit: Energy
      description: Sum of power usage measured at PDU outputs in each rack
    - name: renewable_energy_certificates_joules
      unit: Energy
      description: Energy covered by annually matched green energy certificates
    - name: grid_emission_factor_grams
      unit: Mass
      description: The current grid emission factor (g/CO2-eq per kWh)
    - name: backup_emission_factor_grams
      unit: Mass
      description: The current backup power emission factor (g/CO2-eq per kWh)
    - name: electricity_source
      unit: Value
      description: 1 for grid; 2 for backup generators
    - name: pue_1_ratio
      unit: Percent
      description: Power usage effectiveness measured from the output of the UPS systems
        for IT load
    - name: pue_2_ratio
      unit: Percent
      description: Power usage effectiveness measured from the output of the PDU systems
        for IT load
  x-supported-rack-timeseries-metrics:
    description: List of all supported time series metrics for rack monitoring
    metrics:
    - name: pdu_N_energy_consumption_joules
      unit: Energy
      description: "Energy consumption reading from PDU number N. \nMultiple metrics\
        \ will exist based on number_of_pdus, \ne.g., pdu_1_energy_consumption_joules,\
        \ pdu_2_energy_consumption_joules\n"
    - name: inlet_temperature_celsius
      unit: Temperature
      description: Measurement of inlet cooling temperature (water or air)
    - name: outlet_temperature_celsius
      unit: Temperature
      description: Measurement of outlet cooling temperature (water or air)
  x-supported-server-timeseries-metrics:
    description: List of all supported time series metrics for server monitoring
    metrics:
    - name: cpu_energy_consumption_joules
      unit: Energy
      description: Total energy consumption of all CPUs measured via RAPL
    - name: server_energy_consumption_joules
      unit: Energy
      description: Total energy consumption of the server measured via IPMI
x-tagGroups:
- name: Facility Registry API
  tags:
  - Supported Time Series Metrics for Facilities
  - facility-api.spec_other
- name: Rack Registry API
  tags:
  - Supported Time Series Metrics for Racks
  - rack-api.spec_other
- name: Server Registry API
  tags:
  - Supported Time Series Metrics for Servers
  - server-api.spec_other
